routes/admin.php
<?php

// Authentication Routes...
$this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login');
$this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('admin/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('admin/register', 'Auth\RegisterController@register');

Route::get('/admin', function () {
    return redirect()->route('login');
});

Route::group([
    'prefix' => 'admin/forgot-password',
    'as' => 'forgot-password.',
    'namespace' => 'Backend',
], function () {
    Route::get('/', 'AuthController@forgotPw')->name('index');
    Route::post('send', 'AuthController@sendPw')->name('send');
});

Route::group([
    'prefix' => 'admin/reset-password',
    'as' => 'reset-password.',
    'namespace' => 'Backend',
], function () {
    Route::get('/', 'AuthController@resendPw')->name('index');
    Route::post('update', 'AuthController@updatePw')->name('update');
});

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth'],
    'namespace' => 'Backend',
], function () {

    Route::group([
        'prefix' => 'users',
        'as' => 'users.',
    ], function () {
        Route::get('/', 'UserController@list')->name('list')->middleware(['admin']);
        Route::get('create', 'UserController@create')->name('create')->middleware(['admin']);
        Route::post('store', 'UserController@store')->name('store')->middleware(['admin']);
        Route::delete('{user}/destroy', 'UserController@destroy')->name('destroy')->middleware(['admin']);
        Route::get('{user}/edit', 'UserController@edit')->name('edit');
        Route::post('{user}/update', 'UserController@update')->name('update');
    });

    Route::group([
        'middleware' => ['admin'],
        'prefix' => 'roles',
        'as' => 'roles.',
    ], function () {
        Route::get('/', 'RoleController@list')->name('list');
        Route::get('create', 'RoleController@create')->name('create');
        Route::post('store', 'RoleController@store')->name('store');
        Route::delete('{role}/destroy', 'RoleController@destroy')->name('destroy');
        Route::get('{role}/edit', 'RoleController@edit')->name('edit');
        Route::post('{role}/update', 'RoleController@update')->name('update');
    });

    Route::group([
        'prefix' => 'homepage'
    ],function (){
        Route::get('/', 'HomeController@index')->name('homepage');
    });


    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'banners',
        'as' => 'banners.',
    ], function () {
        Route::get('/', 'BannerController@list')->name('list');
        Route::get('create', 'BannerController@create')->name('create');
        Route::post('store', 'BannerController@store')->name('store');
        Route::get('{banner}/edit', 'BannerController@edit')->name('edit');
        Route::post('{banner}/update', 'BannerController@update')->name('update');
        Route::delete('{banner}/destroy', 'BannerController@destroy')->name('destroy');

    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'contacts',
        'as' => 'contacts.',
    ], function () {
        Route::get('/', 'ContactFormController@list')->name('list');
        Route::get('{contact}/update', 'ContactFormController@update')->name('update');
        Route::get('{contact}/detail', 'ContactFormController@detail')->name('detail');
        Route::post('{contact}/update', 'ContactFormController@update')->name('update');
        Route::delete('{contact}/destroy', 'ContactFormController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'about-us',
        'as' => 'about-us.',
    ], function () {
        Route::get('/', 'AboutUsController@getAbout')->name('index');
        Route::post('save', 'AboutUsController@postAbout')->name('save');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'categories',
        'as' => 'categories.',
    ], function () {
        Route::get('/', 'CategoryController@list')->name('list');
        Route::get('create', 'CategoryController@create')->name('create');
        Route::post('store', 'CategoryController@store')->name('store');
        Route::get('{category}/edit', 'CategoryController@edit')->name('edit');
        Route::post('{category}/update', 'CategoryController@update')->name('update');
        Route::delete('{category}/destroy', 'CategoryController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'articles',
        'as' => 'articles.',
    ], function () {
        Route::get('/', 'ArticleController@list')->name('list');
        Route::get('create', 'ArticleController@create')->name('create');
        Route::post('store', 'ArticleController@store')->name('store');
        Route::get('{article}/edit', 'ArticleController@edit')->name('edit');
        Route::post('{article}/update', 'ArticleController@update')->name('update');
        Route::delete('{article}/destroy', 'ArticleController@destroy')->name('destroy');

    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'holidays',
        'as' => 'holidays.',
    ], function () {
        Route::get('/', 'HolidayController@list')->name('list');
        Route::get('create', 'HolidayController@create')->name('create');
        Route::post('store', 'HolidayController@store')->name('store');
        Route::post('{holiday}/update', 'HolidayController@update')->name('update');
        Route::get('{holiday}/edit', 'HolidayController@edit')->name('edit');
        Route::delete('{holiday}/destroy', 'HolidayController@destroy')->name('destroy');

    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'careers',
        'as' => 'careers.',
    ], function () {
        Route::get('/', 'CareerController@list')->name('list');
        Route::get('create', 'CareerController@create')->name('create');
        Route::post('store', 'CareerController@store')->name('store');
        Route::get('{career}/edit', 'CareerController@edit')->name('edit');
        Route::post('{career}/update', 'CareerController@update')->name('update');
        Route::delete('{career}/destroy', 'CareerController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'application-form',
        'as' => 'application-form.',
    ], function () {
        Route::get('/', 'ApplicationFormController@list')->name('list');
        Route::post('{applicationForm}/update', 'ApplicationFormController@update')->name('update');
        Route::delete('{applicationForm}/destroy', 'ApplicationFormController@destroy')->name('destroy');
        Route::get('{applicationForm}/detail', 'ApplicationFormController@detail')->name('detail');
        Route::get('export', 'ApplicationFormController@export')->name('export');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'contact-us',
        'as' => 'contact-us.',
    ], function () {
        Route::get('/', 'ContactUsController@create')->name('create');
        Route::post('save', 'ContactUsController@postContact')->name('save');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'job-skill-training',
        'as' => 'job-skill-training.',
    ], function () {
        Route::get('/', 'JobskillandTrainingController@list')->name('list');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'clients',
        'as' => 'clients.',
    ], function () {
        Route::get('/', 'ClientController@index')->name('list');
        Route::view('create', 'backend.clients.create')->name('create');
        Route::post('store', 'ClientController@store')->name('store');
        Route::get('{client}/edit', 'ClientController@edit')->name('edit');
        Route::post('{client}/update', 'ClientController@update')->name('update');
        Route::delete('{client}/destroy', 'ClientController@destroy')->name('destroy');
    });
    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'our-businesses',
        'as' => 'our-businesses.',
    ], function () {
        Route::get('/', 'OurBusinessController@index')->name('list');
        Route::get('create', 'OurBusinessController@create')->name('create');
        Route::post('store', 'OurBusinessController@store')->name('store');
        Route::get('{ourBusiness}/edit', 'OurBusinessController@edit')->name('edit');
        Route::post('{ourBusiness}/update', 'OurBusinessController@update')->name('update');
        Route::delete('{ourBusiness}/destroy', 'OurBusinessController@destroy')->name('destroy');
    });
    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'our-services',
        'as' => 'our-services.',
    ], function () {
        Route::get('/', 'OurServiceController@index')->name('list');
        Route::get('create', 'OurServiceController@create')->name('create');
        Route::post('store', 'OurServiceController@store')->name('store');
        Route::get('{ourService}/edit', 'OurServiceController@edit')->name('edit');
        Route::post('{ourService}/update', 'OurServiceController@update')->name('update');
        Route::delete('{ourService}/destroy', 'OurServiceController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['merchant'],
        'prefix' => 'products',
        'as' => 'products.',
        'namespace' => 'Merchant',
    ], function () {
        Route::get('/', 'ProductController@list')->name('list');
        Route::get('create', 'ProductController@create')->name('create');
        Route::post('store', 'ProductController@store')->name('store');
        Route::get('{product}/edit', 'ProductController@edit')->name('edit');

routes/web.php
<?php

Route::group([
    'as' => 'ecommerce.',
    'namespace' => 'Frontend'
], function () {
    Route::get('/', 'FrontEndController@index')->name('list');
    Route::post('store', 'FrontEndController@store')->name('store');
    Route::get('success', 'FrontEndController@success')->name('success');
    Route::get('application-form', 'ApplicationFormController@index')->name('career-form');
    Route::post('save', 'ApplicationFormController@save')->name('save');
    Route::get('about-us', 'AboutUsController@index')->name('about-us');

    Route::group([
        'prefix' => 'article',
    ], function () {
        Route::get('{slug?}/', 'ArticleController@index')->name('article');
        Route::get('{article}/content', 'ArticleController@content')->name('content');
    });

    Route::group([
        'prefix' => 'holiday',
    ], function () {
        Route::get('/', 'HolidayController@index')->name('holiday');
    });

    Route::group([
        'prefix' => 'career',
        'as' => 'career.',
    ], function () {
        Route::get('/', 'CareerController@index')->name('index');
        Route::get('{career}/detail', 'CareerController@detail')->name('detail');
    });

    Route::group([
        'prefix' => 'our-business',
        'as' => 'our-business.',
    ], function () {
        Route::get('/', 'OurBusinessController@index')->name('index');
        Route::get('{ourBusiness}/detail', 'OurBusinessController@detail')->name('detail');
    });

    Route::group([
        'prefix' => 'our-service',
        'as' => 'our-service.',
    ], function () {
        Route::get('/', 'OurServiceController@index')->name('index');
        Route::get('{ourService}/detail', 'OurServiceController@detail')->name('detail');
    });
});


Route::group([
    'prefix' => 'shop',
    'as' => 'merchant.',
    'namespace' => 'Frontend\Merchant'
], function () {
    Route::get('/','ProductController@index');
    Route::post('/payment','ProductController@addOrder');
});

app/Http/Controllers/Backend/AboutUsController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\About;
use Illuminate\Support\Facades\Storage;

class AboutUsController extends Controller
{
    public function getAbout()
    {
        $about = [];
        $oAbout = About::get();
        if ($oAbout->isNotEmpty()) {
            $about = $oAbout;
        }

        return view('backend.about-us.index', compact('about'));
    }

    public function postAbout(Request $request)
    {
        $id = $request->id;
        if (!empty($id)) {
            $this->validateAboutUsEdit($request);
            $data = [
                'title' => $request->title,
                'short_description' => $request->short_description,
                'description' => $request->description,
            ];
            if (!empty($request->image)) {
                $about = About::all()->where('id', $request->id)->first();
                Storage::disk('uploads')->delete($about->image);
                $pathImage = Storage::disk('uploads')->put('about-us', $request->file('image'));
                $data['image'] = $pathImage;
            }
            About::where('id', $request->id)->update($data);

            return redirect()->route('about-us.index')->withSuccess('แก้ไข About Us สำเร็จ');
        } else {

            $this->validateAboutUsCreate($request);
            $pathImage = Storage::disk('uploads')->put('about-us', $request->file('image'));
            $data = [
                'title' => $request->title,
                'short_description' => $request->short_description,
                'description' => $request->description,
                'image' => $pathImage,
            ];
            About::Create($data);

            return redirect()->route('about-us.index')->withSuccess('สร้าง About Us สำเร็จ');
        }
    }

    public function validateAboutUsCreate($request)
    {
        $request->validate([
            'title' => 'required',
            'short_description' => 'required',
            'description' => 'required',
            'image' => 'required|mimes:jpeg,png|max:1024',
        ], [], [
            'title' => 'Title',
            'short_description' => 'Short Description',
            'description' => 'Description',
            'image' => 'Image',
        ]);
    }

    public function validateAboutUsEdit($request)
    {
        $request->validate([
            'title' => 'required',
            'short_description' => 'required',
            'description' => 'required',
            'image' => 'mimes:jpeg,png|max:1024',
        ], [], [
            'title' => 'Title',
            'short_description' => 'Short Description',
            'description' => 'Description',
            'image' => 'Image',
        ]);
    }
}

app/Http/Controllers/Backend/ApplicationFormController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Career;
use App\DataTables\ApplicationFormDataTable;
use App\Exports\ApplicationFormsExport;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ApplicationForm;
use Carbon\Carbon;
use Maatwebsite\Excel\Facades\Excel;

class ApplicationFormController extends Controller
{
    public function list(ApplicationFormDataTable $dataTable)
    {
        $careers = Career::get();

        return $dataTable->render('backend.application-form.list', compact('careers'));
    }

    public function destroy(ApplicationForm $applicationForm)
    {
        if (!request()->ajax()) {
            return response()->json(['error' => 'ไม่สามารถลบข้อมูลได้']);
        }
        $applicationForm->delete();

        return response()->json(['message' => "ลบ Application Form สำเร็จ"]);
    }


    public function detail(ApplicationForm $applicationForm)
    {
        $list['date'] = Carbon::parse($applicationForm->date)->format('d/m/Y');
        $applicationForm = $applicationForm->with('jobSkillTrainings')->find($applicationForm->id);

        return view('backend.application-form.detail', compact('applicationForm', 'list'));
    }

    public function update(ApplicationForm $applicationForm, Request $request)
    {
        $applicationForm->update([
            'status' => $request->status,
        ]);

        return redirect()->route('application-form.list')->withSuccess('แก้ไข Application Form สำเร็จ');
    }

    public function export()
    {
        return Excel::download(new ApplicationFormsExport, 'Application-form-list.xlsx');
    }
}

app/Http/Controllers/Backend/ContactFormController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Contact;
use App\DataTables\ContactFormDataTable;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ContactFormController extends Controller
{
    public function list(ContactFormDataTable $dataTable)
    {
        return $dataTable->render('backend.contact-form.list');
    }

    public function update(Request $request, Contact $contact)
    {
        $contact->update([
                'status' => $request->status,
                'note' => $request->note,
        ]);

        return redirect()->route('contacts.list')->withSuccess('แก้ไข Contact Form สำเร็จ');
    }

    public function detail(Contact $contact)
    {
        $contacts = $contact;

        return view('backend.contact-form.detail', compact('contacts'));
    }

    public function destroy(Contact $contact)
    {
        if(! request()->ajax()){
            return response()->json(['error'=>'Can not Delete']);
        }
        $contact->delete();

        return response()->json(['message' => "ลบ Contact Form สำเร็จ"]);
    }

}

app/Http/Controllers/Backend/Merchant/OrderDetailController.php
<?php

namespace App\Http\Controllers\Backend\Merchant;

use Illuminate\Http\Request;

class OrderDetailController extends Controller
{
   //
}

resources/views/backend/banners/create.blade.php
@extends('backend.layouts.main_dashboard')
@section('title', 'Create Banner')
@section('title_header' , 'Create Banner')
@section('content')
    <div class="box box-primary">
        <form action="{{ route('banners.store') }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="box-body">
                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label>Title <span style="color:red">*</span></label>
                    <input type="text" class="form-control" placeholder="Title" name="title"
                           value="{{ old('title') }}">
                </div>
                <div class="form-group {{ $errors->has('short_description') ? 'has-error' : '' }}">
                    <label>Short Description <span style="color:red">*</span></label>
                    <textarea class="form-control" placeholder="Short Description" name="short_description" rows="4"
                              value="{{ old('short_description') }}"></textarea>
                </div>
                <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                    <label>Image <span style="color:red">*</span></label>
                    <div class="form-group">
                        <div style="display: none " id="divShowImg">
                            <img id="previewBanner">
                            <div><input type="button" value="Clear" onclick="clearBanner()"></div>
                        </div>
                    </div>
                    <input type="file" accept="image/jpeg, image/png" onchange="readBanner(this);" id="fileBanner"
                           name="image">
                    <p class="help-block">
                        ไฟล์ภาพต้องเป็นนามสกุล jpeg,png เท่านั้น <br>
                        ขนาดไฟล์ไม่เกิน 1 MB <br>
                    </p>
                </div>
            </div>
            <div class="box-footer" style="text-align: center">
                <a href="{{ route('banners.list') }}" class="btn btn-danger btn-sm"><i class="fa fa-arrow-left"></i>
                    Back</a>
                <button type="submit" class="btn btn-success btn-sm">
                    <i class="fa fa-floppy-o"></i> Save
                </button>
            </div>
        </form>
    </div>

@endsection

@push('script')
    <script language="javascript" type="text/javascript">
        function readBanner(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#falseinput').attr('src', e.target.result);
                    $('#previewBanner').attr('src', e.target.result);
                    $('#divShowImg').show();
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        function clearBanner() {
            $('#divShowImg').hide();
            $('#previewBanner').attr('src', '');
            $('#fileBanner').val(null);
        }

    </script>

@endpush

resources/views/backend/banners/edit.blade.php
@extends('backend.layouts.main_dashboard')
@section('title', 'Edit Banner')
@section('title_header' , 'Edit Banner')
@section('content')
    <div class="box box-primary">
        <form action="{{ route('banners.update',[$banner->id]) }}" method="post" enctype="multipart/form-data">
            @csrf
            <div class="box-body">
                <div class="form-group {{ $errors->has('title') ? 'has-error' : '' }}">
                    <label>Title <span style="color:red">*</span></label>
                    <input type="text" class="form-control" placeholder="Title" name="title"
                           value="{{ $banner->title }}">
                </div>
                <div class="form-group {{ $errors->has('short_description') ? 'has-error' : '' }}">
                    <label>Short Description <span style="color:red">*</span></label>
                    <textarea class="form-control"
                              name="short_description"
                              placeholder="Short Description" rows="4">{{ $banner->short_description }}</textarea>
                </div>
                <div class="form-group {{ $errors->has('image') ? 'has-error' : '' }}">
                    <label>Image <span style="color:red">*</span></label>
                    <div class="form-group">
                        <a id="linkBanner" href="{{ asset('uploads/'. $banner->image) }}" target="blank">
                            <img id="previewBanner" src="{{ asset('uploads/'. $banner->image) }}"></a>
                        <div><input type="button" value="Clear" onclick="clearPreview()" id="buttonClear"
                                    style="display: none"></div>
                    </div>
                    <input type="file" accept="image/jpeg, image/png"
                           onchange="readBanner(this);" name="image" id="fileBanner">
                    <p class="help-block">
                        ไฟล์ภาพต้องเป็นนามสกุล jpeg,png เท่านั้น <br>
                        ขนาดไฟล์ไม่เกิน 1 MB
                    </p>
                </div>
            </div>
            <div class="box-footer" style="text-align: center">
                <a href="{{ route('banners.list') }}" class="btn btn-danger btn-sm"><i class="fa fa-arrow-left"></i>
                    Back</a>
                <button type="submit" class="btn btn-success btn-sm"><i class="fa fa-floppy-o"></i> Save</button>
            </div>
        </form>
    </div>

@endsection

@push('script')
    <script language="javascript" type="text/javascript">
        function readBanner(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#falseinput').attr('src', e.target.result);
                    $('#previewBanner').attr('src', e.target.result);
                    $('#divShowImg').show();
                };
                reader.readAsDataURL(input.files[0]);
                $('#linkBanner').removeAttr('href');
                $('#buttonClear').show();
            }
        }

        function clearPreview() {
            $('#fileBanner').val(null);
            $('#previewBanner').attr('src', "{{ asset('uploads/'. $banner->image) }}");
            $('#linkBanner').attr('href', "{{ asset('uploads/'. $banner->image) }}");
            $('#buttonClear').hide();
        }

    </script>

@endpush

resources/views/backend/banners/list.blade.php
@extends('backend.layouts.main_dashboard')
@section('title', 'Banner List')
@section('title_header' , 'Banner List')
@section('content')
    <meta name="_token" content="{{ csrf_token() }}"/>
    <div class="row">
        <div class="col-xs-12">
            <div class="box box-primary">
                <div class="box-body">
                    <div class="float-md-right">
                        <a href="{{ route('banners.create') }}" class="btn btn-success btn-sm">
                            <i class="fa fa-plus"></i>
                            Create Banner
                        </a>
                    </div>
                    <div class="box-body table-responsive no-padding">
                        <div class="table table-hover">
                            {!! $dataTable->table(['class' => 'table table-bordered table-responsive data-table',
                            'id' => 'tableBanner', 'style' => 'width:100%']) !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

@push('script')
    <script language="javascript" type="text/javascript">
        $(document).ready(function () {
                $(document).on('click', '.btn-delete', function (e) {
                    e.preventDefault();
                    swal({
                        text: "ยืนยันการลบข้อมูล",
                        icon: "warning",
                        buttons: true,
                        dangerMode: true,
                    })
                        .then((willDelete) => {
                            if (willDelete) {
                                var param = $(this).data('url');
                                var method_type = 'DELETE';

                                if ($(this).data('method-type')) {
                                    method_type = $(this).data('method-type');
                                }
                                $.ajax({
                                    headers: {
                                        'X-CSRF-TOKEN': $('meta[name="_token"]').attr('content')
                                    },
                                    dataType: 'json',
                                    url: param,
                                    type: method_type,
                                    _token: '{{ csrf_field() }}',

                                }).done(function (data) {
                                    swal(data.message, {
                                        icon: "success",
                                    });
                                    $('.data-table').DataTable().draw();
                                });
                            }
                        });
                });
        });
    </script>
    {!! $dataTable->scripts() !!}

@endpush