routes/admin.php
<?php

// Authentication Routes...
$this->get('admin/login', 'Auth\LoginController@showLoginForm')->name('login');
$this->post('admin/login', 'Auth\LoginController@login');
$this->get('admin/logout', 'Auth\LoginController@logout')->name('logout');

// Registration Routes...
$this->get('admin/register', 'Auth\RegisterController@showRegistrationForm')->name('register');
$this->post('admin/register', 'Auth\RegisterController@register');

Route::get('/admin', function () {
    return redirect()->route('login');
});

Route::group([
    'prefix' => 'admin/forgot-password',
    'as' => 'forgot-password.',
    'namespace' => 'Backend',
], function () {
    Route::get('/', 'AuthController@forgotPw')->name('index');
    Route::post('send', 'AuthController@sendPw')->name('send');
});

Route::group([
    'prefix' => 'admin/reset-password',
    'as' => 'reset-password.',
    'namespace' => 'Backend',
], function () {
    Route::get('/', 'AuthController@resendPw')->name('index');
    Route::post('update', 'AuthController@updatePw')->name('update');
});

Route::group([
    'prefix' => 'admin',
    'middleware' => ['auth'],
    'namespace' => 'Backend',
], function () {

    Route::group([
        'prefix' => 'users',
        'as' => 'users.',
    ], function () {
        Route::get('/', 'UserController@list')->name('list')->middleware(['admin']);
        Route::get('create', 'UserController@create')->name('create')->middleware(['admin']);
        Route::post('store', 'UserController@store')->name('store')->middleware(['admin']);
        Route::delete('{user}/destroy', 'UserController@destroy')->name('destroy')->middleware(['admin']);
        Route::get('{user}/edit', 'UserController@edit')->name('edit');
        Route::post('{user}/update', 'UserController@update')->name('update');
    });

    Route::group([
        'middleware' => ['admin'],
        'prefix' => 'roles',
        'as' => 'roles.',
    ], function () {
        Route::get('/', 'RoleController@list')->name('list');
        Route::get('create', 'RoleController@create')->name('create');
        Route::post('store', 'RoleController@store')->name('store');
        Route::delete('{role}/destroy', 'RoleController@destroy')->name('destroy');
        Route::get('{role}/edit', 'RoleController@edit')->name('edit');
        Route::post('{role}/update', 'RoleController@update')->name('update');
    });

    Route::group([
        'prefix' => 'homepage'
    ],function (){
        Route::get('/', 'HomeController@index')->name('homepage');
    });


    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'banners',
        'as' => 'banners.',
    ], function () {
        Route::get('/', 'BannerController@list')->name('list');
        Route::get('create', 'BannerController@create')->name('create');
        Route::post('store', 'BannerController@store')->name('store');
        Route::get('{banner}/edit', 'BannerController@edit')->name('edit');
        Route::post('{banner}/update', 'BannerController@update')->name('update');
        Route::delete('{banner}/destroy', 'BannerController@destroy')->name('destroy');

    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'contacts',
        'as' => 'contacts.',
    ], function () {
        Route::get('/', 'ContactFormController@list')->name('list');
        Route::get('{contact}/update', 'ContactFormController@update')->name('update');
        Route::get('{contact}/detail', 'ContactFormController@detail')->name('detail');
        Route::post('{contact}/update', 'ContactFormController@update')->name('update');
        Route::delete('{contact}/destroy', 'ContactFormController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'about-us',
        'as' => 'about-us.',
    ], function () {
        Route::get('/', 'AboutUsController@getAbout')->name('index');
        Route::post('save', 'AboutUsController@postAbout')->name('save');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'categories',
        'as' => 'categories.',
    ], function () {
        Route::get('/', 'CategoryController@list')->name('list');
        Route::get('create', 'CategoryController@create')->name('create');
        Route::post('store', 'CategoryController@store')->name('store');
        Route::get('{category}/edit', 'CategoryController@edit')->name('edit');
        Route::post('{category}/update', 'CategoryController@update')->name('update');
        Route::delete('{category}/destroy', 'CategoryController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'articles',
        'as' => 'articles.',
    ], function () {
        Route::get('/', 'ArticleController@list')->name('list');
        Route::get('create', 'ArticleController@create')->name('create');
        Route::post('store', 'ArticleController@store')->name('store');
        Route::get('{article}/edit', 'ArticleController@edit')->name('edit');
        Route::post('{article}/update', 'ArticleController@update')->name('update');
        Route::delete('{article}/destroy', 'ArticleController@destroy')->name('destroy');

    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'holidays',
        'as' => 'holidays.',
    ], function () {
        Route::get('/', 'HolidayController@list')->name('list');
        Route::get('create', 'HolidayController@create')->name('create');
        Route::post('store', 'HolidayController@store')->name('store');
        Route::post('{holiday}/update', 'HolidayController@update')->name('update');
        Route::get('{holiday}/edit', 'HolidayController@edit')->name('edit');
        Route::delete('{holiday}/destroy', 'HolidayController@destroy')->name('destroy');

    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'careers',
        'as' => 'careers.',
    ], function () {
        Route::get('/', 'CareerController@list')->name('list');
        Route::get('create', 'CareerController@create')->name('create');
        Route::post('store', 'CareerController@store')->name('store');
        Route::get('{career}/edit', 'CareerController@edit')->name('edit');
        Route::post('{career}/update', 'CareerController@update')->name('update');
        Route::delete('{career}/destroy', 'CareerController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'application-form',
        'as' => 'application-form.',
    ], function () {
        Route::get('/', 'ApplicationFormController@list')->name('list');
        Route::post('{applicationForm}/update', 'ApplicationFormController@update')->name('update');
        Route::delete('{applicationForm}/destroy', 'ApplicationFormController@destroy')->name('destroy');
        Route::get('{applicationForm}/detail', 'ApplicationFormController@detail')->name('detail');
        Route::get('export', 'ApplicationFormController@export')->name('export');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'contact-us',
        'as' => 'contact-us.',
    ], function () {
        Route::get('/', 'ContactUsController@create')->name('create');
        Route::post('save', 'ContactUsController@postContact')->name('save');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'job-skill-training',
        'as' => 'job-skill-training.',
    ], function () {
        Route::get('/', 'JobskillandTrainingController@list')->name('list');
    });

    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'clients',
        'as' => 'clients.',
    ], function () {
        Route::get('/', 'ClientController@index')->name('list');
        Route::view('create', 'backend.clients.create')->name('create');
        Route::post('store', 'ClientController@store')->name('store');
        Route::get('{client}/edit', 'ClientController@edit')->name('edit');
        Route::post('{client}/update', 'ClientController@update')->name('update');
        Route::delete('{client}/destroy', 'ClientController@destroy')->name('destroy');
    });
    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'our-businesses',
        'as' => 'our-businesses.',
    ], function () {
        Route::get('/', 'OurBusinessController@index')->name('list');
        Route::get('create', 'OurBusinessController@create')->name('create');
        Route::post('store', 'OurBusinessController@store')->name('store');
        Route::get('{ourBusiness}/edit', 'OurBusinessController@edit')->name('edit');
        Route::post('{ourBusiness}/update', 'OurBusinessController@update')->name('update');
        Route::delete('{ourBusiness}/destroy', 'OurBusinessController@destroy')->name('destroy');
    });
    Route::group([
        'middleware' => ['writer'],
        'prefix' => 'our-services',
        'as' => 'our-services.',
    ], function () {
        Route::get('/', 'OurServiceController@index')->name('list');
        Route::get('create', 'OurServiceController@create')->name('create');
        Route::post('store', 'OurServiceController@store')->name('store');
        Route::get('{ourService}/edit', 'OurServiceController@edit')->name('edit');
        Route::post('{ourService}/update', 'OurServiceController@update')->name('update');
        Route::delete('{ourService}/destroy', 'OurServiceController@destroy')->name('destroy');
    });

    Route::group([
        'middleware' => ['merchant'],
        'prefix' => 'products',
        'as' => 'products.',
        'namespace' => 'Merchant',
    ], function () {
        Route::get('/', 'ProductController@list')->name('list');
        Route::get('create', 'ProductController@create')->name('create');
        Route::post('store', 'ProductController@store')->name('store');
        Route::get('{product}/edit', 'ProductController@edit')->name('edit');

routes/web.php
<?php

Route::group([
    'as' => 'ecommerce.',
    'namespace' => 'Frontend'
], function () {
    Route::get('/', 'FrontEndController@index')->name('list');
    Route::post('store', 'FrontEndController@store')->name('store');
    Route::get('success', 'FrontEndController@success')->name('success');
    Route::get('application-form', 'ApplicationFormController@index')->name('career-form');
    Route::post('save', 'ApplicationFormController@save')->name('save');
    Route::get('about-us', 'AboutUsController@index')->name('about-us');

    Route::group([
        'prefix' => 'article',
    ], function () {
        Route::get('{slug?}/', 'ArticleController@index')->name('article');
        Route::get('{article}/content', 'ArticleController@content')->name('content');
    });

    Route::group([
        'prefix' => 'holiday',
    ], function () {
        Route::get('/', 'HolidayController@index')->name('holiday');
    });

    Route::group([
        'prefix' => 'career',
        'as' => 'career.',
    ], function () {
        Route::get('/', 'CareerController@index')->name('index');
        Route::get('{career}/detail', 'CareerController@detail')->name('detail');
    });

    Route::group([
        'prefix' => 'our-business',
        'as' => 'our-business.',
    ], function () {
        Route::get('/', 'OurBusinessController@index')->name('index');
        Route::get('{ourBusiness}/detail', 'OurBusinessController@detail')->name('detail');
    });

    Route::group([
        'prefix' => 'our-service',
        'as' => 'our-service.',
    ], function () {
        Route::get('/', 'OurServiceController@index')->name('index');
        Route::get('{ourService}/detail', 'OurServiceController@detail')->name('detail');
    });
});


Route::group([
    'prefix' => 'shop',
    'as' => 'merchant.',
    'namespace' => 'Frontend\Merchant'
], function () {
    Route::get('/','ProductController@index');
    Route::post('/payment','ProductController@addOrder');
});

app/Http/Controllers/Frontend/AboutUsController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\About;
use App\ContactUs;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AboutUsController extends Controller
{
    public function index()
    {
        $contactUses = ContactUs::get();
        $aboutUses = About::first();
        return view('frontend.about-us.index', compact('contactUses', 'aboutUses'));
    }
}

app/Http/Controllers/Frontend/ApplicationFormController.php
<?php

namespace App\Http\Controllers\Frontend;

use Carbon\Carbon;
use App\ApplicationForm;
use App\Career;
use App\ContactUs;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\JobSkillTraining;
use Illuminate\Support\Facades\Storage;

class ApplicationFormController extends Controller
{
    public function index()
    {
        $contactUses = ContactUs::get();
        $careers = Career::where('status', 'Open')->get();

        return view('frontend.application-form.index', compact('contactUses', 'careers'));
    }

    public function save(Request $request)
    {
        $this->validateCareer($request);
        $contactUses = ContactUs::get();
        $check = Career::where('status', 'Open')
            ->where('id', $request->position)
            ->first();

        if (empty($check)) {
            return redirect()->route('ecommerce.career');
        }

        $attach = Storage::disk('uploads')->put('attach/pdf', $request->file('attach'));
        $input = [
            'firstname' => $request->firstname,
            'lastname' => $request->lastname,
            'date' => Carbon::createFromFormat('d/m/Y', $request->date),
            'phone' => $request->phone,
            'email' => $request->email,
            'university' => $request->university,
            'degree' => $request->degree,
            'subject' => $request->major,
            'gpa' => $request->gpa,
            'career_id' => $request->position,
            'expected_salary' => $request->salary,
            'status' => 'Waiting',
            'attach' => $attach,
        ];
        $applicationForm = ApplicationForm::Create($input);
        if (count($request->company) > 10) {
            return redirect()->route('ecommerce.career');
        }
        if (empty($request->checkbox)) {
            for ($i = 0; $i < count($request->company); $i++) {
                $work_experience = [
                    "company_name" => $request->company[$i],
                    "job_title" => $request->job_title[$i],
                    "date_start" => Carbon::createFromFormat('d/m/Y', $request->start_date[$i]),
                    "date_end" => Carbon::createFromFormat('d/m/Y', $request->end_date[$i]),
                    "job_description" => $request->responsibilities[$i],
                    "application_form_id" => $applicationForm->id,
                ];
                JobSkillTraining::Create($work_experience);
            }
        }

        return redirect()->route('ecommerce.success',compact('contactUses'))->withSuccess('Send Success');

    }

    public function validateCareer($request)
    {
        $input = [
            'firstname' => 'required',
            'lastname' => 'required',
            'date' => 'required|date_format:"d/m/Y"',
            'phone' => 'required|numeric|digits_between:1,10',
            'email' => 'required|email',
            'university' => 'required',
            'degree' => 'required',
            'major' => 'required',
            'gpa' => 'required',
            'position' => 'required',
            'salary' => 'required|numeric|digits_between:0,7|min:1',
            'attach' => 'required|mimes:pdf|max:1024',
        ];

        if (empty($request->checkbox)) {
            $input += [
                'company.*' => 'required',
                'job_title.*' => 'required',
                'start_date.*' => 'required|date_format:"d/m/Y"|before_or_equal:end_date.*',
                'end_date.*' => 'required|date_format:"d/m/Y"|after_or_equal:start_date.*',
                'responsibilities.*' => 'required',
            ];
        }

        $custom = [
            'firstname' => 'First name',
            'lastname' => 'Last name',
            'date' => 'Birthdate',
            'phone' => 'Contact Number',
            'email' => 'Email',
            'university' => 'University',
            'degree' => 'Degree',
            'major' => 'Major/Subject',
            'gpa' => 'GPA',
            'position' => 'Position',
            'salary' => 'Salary',
            'attach' => 'Attach',
            'company.*' => 'Company',
            'job_title.*' => 'Job Title',
            'start_date.*' => 'Date Start',
            'end_date.*' => "Date End",
            'responsibilities.*' => 'Responsibilities',
        ];

        $request->validate($input, [], $custom);
    }
}

app/Http/Controllers/Frontend/CareerController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Career;
use App\ContactUs;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CareerController extends Controller
{
    public function index()
    {
        $contactUses = ContactUs::get();
        $careers = Career::where('status', 'Open')->get();

        return view('frontend.careers.index', compact('contactUses', 'careers'));
    }

    public function detail(Career $career)
    {
        $contactUses = ContactUs::get();

        return view('frontend.careers.detail', compact('contactUses', 'career'));
    }
}

app/Http/Controllers/Frontend/HolidayController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Holiday;
use App\ContactUs;
use App\Http\Controllers\Controller;

class HolidayController extends Controller
{
    public function index()
    {
        $holidays = Holiday::get();
        $contactUses = ContactUs::get();

        return view('frontend.holidays.index',compact('contactUses','holidays'));
    }
}

resources/views/frontend/partials/about-us.blade.php
@if($aboutUses !=null)
    <section class="section-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-6 box-bg ">
                    <div class="box-left animatedParent animateOnce" data-sequence='500' data-appear-top-offset='-300'>
                        <div class="title title-white text-left">{{ $aboutUses->title }}</div>
                        <div class="caption caption-white text-left">
                            {!! $aboutUses->short_description !!}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@else
@endif

resources/views/frontend/partials/benefit-career.blade.php
<section class="section-benefits">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="title title-white">Benefits</div>
                <div class="row item-benefits justify-content-center">
                    <div class="col-sm-2">
                        <div class="item text-center align-items-center">
                            <div class="item-image">
                                <img src="{{ asset('img/b1.png') }}" alt="">
                            </div>
                            <div class="item-title">ประกันสังคม<br/>ประกันสุขภาพ</div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="item text-center align-items-center">
                            <div class="item-image">
                                <img src="{{ asset('img/b2.png') }}" alt="">
                            </div>
                            <div class="item-title">
                                โบนัสประจำปี
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="item text-center align-items-center">
                            <div class="item-image">
                                <img src="{{ asset('img/b3.png') }}" alt="">
                            </div>
                            <div class="item-title">
                                ท่องเที่ยวประจำปี
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="item text-center align-items-center">
                            <div class="item-image">
                                <img src="{{ asset('img/b4.png') }}" alt="">
                            </div>
                            <div class="item-title">
                                มินิมาร์ท<br/> ขนม&เครื่องดื่ม
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-2">
                        <div class="item text-center align-items-center">
                            <div class="item-image">
                                <img src="{{ asset('img/b5.png') }}" alt="">
                            </div>
                            <div class="item-title">
                                เล่นกีฬา<br/>แบตมินตัน ฟุตบอล
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

resources/views/frontend/partials/contact-form.blade.php
@if(!$contactUses->isEmpty())
    <section class="section-5">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                    @foreach($contactUses as $contactUs)
                        <div class="title title-white">{{ ($contactUs->title) }}</div>
                        <div class="caption caption-white text-left">
                            {!! $contactUs->short_description !!}
                        </div>
                        <div>
                            @if(!$contactUs->time==null)
                            <i class="fas fa-clock icon-color"></i> <span
                                    class="caption caption-white"> {{ $contactUs->time }} </span>
                                @else
                                @endif
                        </div>
                    @endforeach
            </div>
            <div class="col-sm-8">
                <form action="{{ route('ecommerce.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    <div class="row form-message">
                        <div class="form-group col-sm-6">
                            <input type="text" class="form-control" placeholder="Name" name="name">
                        </div>
                        <div class="form-group col-sm-6">
                            <input type="text" class="form-control" placeholder="Email" name="email">
                        </div>
                        <div class="form-group col-sm-6">
                            <input type="text"  id="phone_number" class="form-control" placeholder="Phone" name="tel">
                        </div>
                        <div class="form-group col-sm-6">
                            <input type="text" class="form-control" placeholder="Company" name="company">
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="comment">Message:</label>
                            <textarea class="form-control" rows="4" name="message"></textarea>
                        </div>
                        <div class="col-sm-12">
                            <button type="submit" class="btn btn-style">Send Message</button>
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </form>
            </div>
        </div>
    </div>
</section>
@else
@endif
@push('script')
    <script>

        new Cleave('#phone_number', {
            phone: true,
            delimiter: ' ',
            phoneRegionCode: 'TH'
        });

    </script>
@endpush

resources/views/frontend/partials/navbar.blade.php
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{{ route('ecommerce.list') }}"><img src="{{ asset('img/logo.png') }}"/></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{ route('ecommerce.list') }}">Home
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('ecommerce.about-us') }}">About Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('ecommerce.article') }}">Article</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle"  href="#" id="navbar-dropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Our Businesses</a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbar-dropdown">
                        <a class="dropdown-item" href="{{ route('ecommerce.our-business.index') }}">Our Business</a>
                        <a class="dropdown-item" href="{{ route('ecommerce.our-service.index') }}">Our Service</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('ecommerce.career.index') }}">Career</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('ecommerce.holiday') }}">Holiday</a>
                </li>
                <li class="nav-item language">
                    <a class="nav-link" href=""><img src="{{ asset('img/flag-th.png') }}">
                        <label>ไทย</label></a>
                </li>
            </ul>
        </div>
    </div>
</nav>

resources/views/frontend/partials/our-service.blade.php
@if(!$ourServices->isEmpty())
    <section class="section-3">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="title title-black">OUR SERVICE</div>
                    <div class="caption caption-black text-center">บริการของเรา</div>
                </div>
                <div class="service">
                    <div class="container ">
                        <div class="row">
                            @foreach($ourServices as $key =>$ourService)
                                @if($key%2==0)
                                    <div class="col-sm-6 column-xs">
                                        <div class="row">
                                            <div class="item col-sm-12">
                                                <div class="thumbnail">
                                                    <div class="item-image">
                                                        <a href="{{ route('ecommerce.our-service.detail', [$ourService->id]) }}">
                                                            <div class="image image-1"><img
                                                                    src="{{ asset('uploads/'.$ourService->image) }}"
                                                                    alt="image"></div>
                                                        </a>
                                                    </div>
                                                    <div class="caption">
                                                        <div class="title">
                                                            {{  $ourService->title }}
                                                        </div>
                                                        <div class="item-description">
                                                            {{ $ourService->short_description }}
                                                        </div>
                                                        <div class="item-readmore">
                                                            <a href="{{ route('ecommerce.our-service.detail', [$ourService->id]) }}">view
                                                                more</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @else
                                    <div class="col-sm-6 column-xs">
                                        <div class="row">
                                            <div class="item col-sm-12">
                                                <div class="thumbnail">
                                                    <div class="item-image">
                                                        <a href="{{ route('ecommerce.our-service.detail', [$ourService->id]) }}">
                                                            <div class="image image-1"><img
                                                                    src="{{ asset('uploads/'.$ourService->image) }}"
                                                                    alt="image"></div>
                                                        </a>
                                                    </div>
                                                    <div class="caption">
                                                        <div class="title">
                                                            {{ $ourService->title }}
                                                        </div>
                                                        <div class="item-description">
                                                            {{ $ourService->short_description }}
                                                        </div>
                                                        <div class="item-readmore">
                                                            <a href="{{ route('ecommerce.our-service.detail', [$ourService->id]) }}">view
                                                                more</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endif